Fix issues discovered during attempted upgrade using 2.1.1-RC3.
Remove unnecessary explicit version for postgresql, fixing "Duplicating managed version 42.3.3 for postgresql".

Exclude old conflicting versions of apache commons-io from WRO dependencies, fixing java.lang.NoSuchMethodError: 'java.lang.String org.apache.commons.io.IOUtils.toString(java.io.InputStream, java.nio.charset.Charset).
The latest commons-io is explicitly added.

Add data typs for FilterRegistrationBean, fixing "FilterRegistrationBean is a raw type. References to generic type FilterRegistrationBean<T> should be parameterized"

Add `<?>` to `Enum`, fixing warning.

Replace ObjectMapper instantiation with JsonMapper.builder().
This makes the code cleaner and removes deprecated warnings.

Replace `new Long(1);` with `Long.valueOf(1);`, fixing warning "The constructor Long(long) is deprecated since version 9".